required = [
  "k8s.io/code-generator/cmd/client-gen",
  "k8s.io/code-generator/cmd/conversion-gen",
  "k8s.io/code-generator/cmd/deepcopy-gen",
  "k8s.io/code-generator/cmd/defaulter-gen",
  "k8s.io/code-generator/cmd/informer-gen",
  "k8s.io/code-generator/cmd/lister-gen",
  "github.com/onsi/ginkgo/ginkgo",
]

[[constraint]]
  name = "github.com/sirupsen/logrus"
  version = "1.0.5"

[[constraint]]
  name = "k8s.io/client-go"
  version = "v11.0.0"

[[constraint]]
  name = "github.com/onsi/ginkgo"
  version = "1.6.0"

[[constraint]]
  name = "github.com/onsi/gomega"
  version = "1.3.0"

[[constraint]]
  name = "github.com/prometheus/client_golang"
  version = "v0.8.0"

[[constraint]]
  name = "github.com/spf13/cobra"
  version = "0.0.3"

[[constraint]]
  name = "k8s.io/apimachinery"
  version = "kubernetes-1.14.1"

[[constraint]]
  name = "k8s.io/code-generator"
  version = "kubernetes-1.14.1"

[[override]]
  # required to work around a bug in dep: https://github.com/golang/dep/issues/1799
  source = "https://github.com/fsnotify/fsnotify/archive/v1.4.7.tar.gz"
  name = "gopkg.in/fsnotify.v1"

[[constraint]]
  name = "github.com/PaesslerAG/jsonpath"
  version = "v0.1.0"

[[constraint]]
  name = "github.com/robfig/cron"
  version = "1.1"

[prune]
  go-tests = true
  # unused-packages = true
