apiVersion: v1
kind: ServiceAccount
metadata:
  name: cassandra-snapshot
  namespace: $TARGET_NAMESPACE
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: cassandra-snapshot
rules:
- apiGroups: [""]
  resources: ["pods"]
  verbs: ["list"]
- apiGroups: [""]
  resources: ["pods/exec"]
  verbs: ["create"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: cassandra-snapshot-binding
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: cassandra-snapshot
subjects:
- kind: ServiceAccount
  name: cassandra-snapshot
  namespace: $TARGET_NAMESPACE

