[[constraint]]
  name = "github.com/sirupsen/logrus"
  version = "1.0.5"

[[constraint]]
  name = "k8s.io/client-go"
  version = "v7.0.0"

[[override]]
  source = "https://github.com/fsnotify/fsnotify/archive/v1.4.7.tar.gz"
  name = "gopkg.in/fsnotify.v1"

[[constraint]]
  name = "github.com/onsi/ginkgo"
  version = "1.6.0"

[[constraint]]
  name = "github.com/onsi/gomega"
  version = "1.3.0"

[[constraint]]
  name = "github.com/spf13/cobra"
  version = "0.0.3"

[[override]]
  name = "k8s.io/apimachinery"
  revision = "800fcb029b488923f14852306f0c98c11d0f360c"

[prune]
  go-tests = true
